stages:
  - deploy
  
deploy_dev:
    before_script:
      - sleep 10
      - ip a
      - sudo chmod 777 -R /home/gitlab-runner/
      - sudo apt install -y python3
      - sudo apt install -y python3-pip
      - sudo apt install -y python3-pip
      - whoami
      - pwd
      - sudo pip3 install -r requirements.txt
    variables:
      GIT_STRATEGY: clone
    stage: deploy
    script:
      - whoami
      - pwd
      - sudo systemctl restart uwsgi
      - echo "Deploy to development server"

    environment:
      name: main
      url: 
    tags:
      - main
    only:
      - main
 

